package webui

const dashboardV2HTML = `<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="color-scheme" content="light">
<title>GoProxy Plus · 代理调度中心</title>
<style>
*{box-sizing:border-box}html{scroll-behavior:smooth}body,h1,h2,h3,p{margin:0}
:root{
  --canvas:#f4f6fa;--surface:#fff;--surface-soft:#f8fafc;--ink:#172033;--muted:#687386;
  --line:#e3e8f0;--line-strong:#d3dae6;--accent:#2d63d6;--accent-soft:#edf3ff;
  --good:#16845a;--warn:#b86a18;--bad:#c04457;--nav:#111827;--nav-muted:#9aa7bb;
  --radius:18px;--radius-sm:11px;--shadow:0 18px 48px rgba(24,36,58,.08);
  --font:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif;
  --mono:"SFMono-Regular",Consolas,"Liberation Mono",monospace
}
body{min-height:100vh;background:var(--canvas);color:var(--ink);font:14px/1.5 var(--font);-webkit-font-smoothing:antialiased}
button,input,select{font:inherit}button{color:inherit}.icon{width:18px;height:18px;display:block;flex:0 0 auto}
.app-shell{display:grid;grid-template-columns:244px minmax(0,1fr);min-height:100vh}
.rail{position:sticky;top:0;height:100vh;padding:22px 16px;background:var(--nav);color:#fff;display:flex;flex-direction:column;z-index:30}
.brand{display:flex;align-items:center;gap:12px;padding:3px 8px 24px}.brand-mark{width:38px;height:38px;border-radius:12px;background:linear-gradient(145deg,#5f8df0,#315fca);display:grid;place-items:center;font-weight:800;letter-spacing:-.04em;box-shadow:0 10px 24px rgba(45,99,214,.35)}
.brand-name{font-size:15px;font-weight:720;letter-spacing:-.01em}.brand-sub{font-size:11px;color:var(--nav-muted);margin-top:1px}
.nav-label{padding:0 12px;margin:8px 0 7px;color:#718096;font-size:10px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}
.nav{display:grid;gap:5px}.nav a{display:flex;align-items:center;gap:11px;padding:10px 12px;border-radius:10px;color:var(--nav-muted);text-decoration:none;font-size:13px;font-weight:620;transition:background .16s ease,color .16s ease,transform .1s ease}.nav a:hover,.nav a:focus-visible{background:rgba(255,255,255,.08);color:#fff;outline:0}.nav a:active{transform:scale(.98)}
.rail-foot{margin-top:auto;padding:14px 10px 4px;border-top:1px solid rgba(255,255,255,.09)}.role-line{display:flex;align-items:center;justify-content:space-between;gap:10px}.role{display:flex;align-items:center;gap:8px;color:#d7deea;font-size:12px}.role-dot{width:7px;height:7px;border-radius:50%;background:#4ade80;box-shadow:0 0 0 4px rgba(74,222,128,.1)}.rail-link{color:var(--nav-muted);font-size:11px;text-decoration:none}.rail-link:hover{color:#fff}
.workspace{min-width:0;padding:26px clamp(18px,3vw,42px) 64px}.workspace-inner{max-width:1500px;margin:0 auto}
.topbar{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;margin-bottom:25px}.eyebrow{color:var(--accent);font-size:11px;font-weight:750;letter-spacing:.08em;text-transform:uppercase;margin-bottom:6px}.page-title{font-size:clamp(26px,3vw,38px);line-height:1.08;letter-spacing:-.045em;font-weight:760}.page-copy{margin-top:8px;color:var(--muted);font-size:13px}.top-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap;justify-content:flex-end}
.btn{min-height:38px;padding:8px 13px;border:1px solid var(--line);border-radius:10px;background:var(--surface);color:var(--ink);font-size:12px;font-weight:680;display:inline-flex;align-items:center;justify-content:center;gap:8px;cursor:pointer;text-decoration:none;box-shadow:0 1px 2px rgba(20,31,50,.03);transition:background .16s ease,border-color .16s ease,transform .1s ease,box-shadow .16s ease}.btn:hover{background:var(--surface-soft);border-color:var(--line-strong)}.btn:active{transform:scale(.975)}.btn:focus-visible{outline:0;box-shadow:0 0 0 4px rgba(45,99,214,.14)}.btn-primary{background:var(--accent);border-color:var(--accent);color:#fff}.btn-primary:hover{background:#2457c1;border-color:#2457c1}.btn-danger{color:var(--bad);border-color:#efcbd2}.btn-danger:hover{background:#fff3f5}.btn-quiet{background:transparent;box-shadow:none}.btn-icon{width:38px;padding:0}.btn[disabled]{opacity:.5;cursor:not-allowed}
.status-strip{position:relative;overflow:hidden;background:linear-gradient(125deg,#18243a,#24365a);color:#fff;border-radius:22px;padding:22px 24px;box-shadow:var(--shadow);margin-bottom:16px}.status-strip:after{content:"";position:absolute;width:320px;height:320px;right:-120px;top:-210px;border-radius:50%;background:rgba(103,137,222,.25)}.status-main{position:relative;z-index:1;display:flex;align-items:center;justify-content:space-between;gap:24px}.status-copy{display:flex;align-items:center;gap:13px}.status-orb{width:12px;height:12px;border-radius:50%;background:#4ade80;box-shadow:0 0 0 7px rgba(74,222,128,.12)}.status-orb.warning{background:#f5a64b;box-shadow:0 0 0 7px rgba(245,166,75,.12)}.status-orb.critical,.status-orb.emergency{background:#fb7185;box-shadow:0 0 0 7px rgba(251,113,133,.12)}.status-title{font-size:17px;font-weight:720;letter-spacing:-.015em}.status-meta{font-size:11px;color:#b9c5d8;margin-top:3px}.status-total{text-align:right}.status-total strong{font-size:34px;line-height:1;font-weight:740;letter-spacing:-.04em;font-variant-numeric:tabular-nums}.status-total span{display:block;color:#b9c5d8;font-size:11px;margin-top:5px}
.metric-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:12px;margin-bottom:24px}.metric{background:var(--surface);border:1px solid var(--line);border-radius:15px;padding:15px 16px;min-width:0}.metric-label{font-size:11px;color:var(--muted);font-weight:650}.metric-value{margin-top:7px;font-size:25px;line-height:1.05;letter-spacing:-.035em;font-weight:730;font-variant-numeric:tabular-nums}.metric-meta{margin-top:6px;color:#8b95a6;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.tone-good{color:var(--good)}.tone-warn{color:var(--warn)}.tone-bad{color:var(--bad)}
.section{margin-top:24px;scroll-margin-top:20px;content-visibility:auto;contain-intrinsic-size:520px}.section-head{display:flex;align-items:flex-end;justify-content:space-between;gap:18px;margin-bottom:11px}.section-title{font-size:18px;font-weight:740;letter-spacing:-.025em}.section-copy{font-size:11px;color:var(--muted);margin-top:3px}.section-actions{display:flex;gap:8px;align-items:center}
.split{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(340px,.8fr);gap:14px}.card{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);padding:19px}.card-title{font-size:13px;font-weight:710}.card-sub{font-size:10px;color:var(--muted);margin-top:3px}.quality-track{height:12px;border-radius:999px;background:#eef1f5;overflow:hidden;display:flex;margin:24px 0 17px}.quality-segment{height:100%;min-width:0;transition:width .28s ease}.quality-s{background:#2f9e75}.quality-a{background:#d3a137}.quality-b{background:#da7d37}.quality-c{background:#c95164}.legend{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.legend-item{padding:10px;border-radius:10px;background:var(--surface-soft);display:flex;align-items:center;justify-content:space-between;gap:8px;font-size:11px;color:var(--muted)}.legend-item strong{font-size:14px;color:var(--ink);font-variant-numeric:tabular-nums}.legend-dot{width:7px;height:7px;border-radius:50%;display:inline-block;margin-right:6px}
.app-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:14px}.app-stat{padding:11px;border:1px solid var(--line);border-radius:11px}.app-stat span{display:block;color:var(--muted);font-size:10px}.app-stat strong{display:block;margin-top:5px;font-size:18px;letter-spacing:-.025em;font-variant-numeric:tabular-nums}
.table-card{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);overflow:hidden}.filterbar{padding:13px;border-bottom:1px solid var(--line);display:grid;grid-template-columns:minmax(210px,1fr) repeat(5,minmax(105px,auto));gap:8px}.field{position:relative}.field .icon{position:absolute;left:11px;top:50%;transform:translateY(-50%);color:#8994a5;width:16px;height:16px;pointer-events:none}.input,.select{width:100%;min-height:38px;border:1px solid var(--line);border-radius:10px;background:#fff;color:var(--ink);padding:8px 11px;font-size:12px;outline:0}.field .input{padding-left:35px}.input:focus,.select:focus{border-color:#7c9be0;box-shadow:0 0 0 3px rgba(45,99,214,.11)}
.table-scroll{overflow:auto;max-height:680px;contain:strict;min-height:260px}.node-table{width:100%;border-collapse:separate;border-spacing:0;min-width:980px;font-size:12px}.node-table thead{position:sticky;top:0;z-index:4;background:rgba(248,250,252,.97);box-shadow:0 1px 0 var(--line)}.node-table th{height:42px;padding:0 13px;text-align:left;color:#6e7889;font-size:10px;font-weight:720;letter-spacing:.025em;white-space:nowrap}.node-table td{height:49px;padding:8px 13px;border-bottom:1px solid #edf0f4;color:#536074;white-space:nowrap}.node-table tbody tr:last-child td{border-bottom:0}.node-table tbody tr:hover{background:#f8faff}.mono{font-family:var(--mono);font-size:11px}.address-btn{max-width:235px;border:0;background:transparent;padding:0;color:#2e5dbf;cursor:pointer;overflow:hidden;text-overflow:ellipsis;vertical-align:middle;text-align:left}.address-btn:hover{text-decoration:underline}.chip{display:inline-flex;align-items:center;min-height:23px;padding:2px 8px;border-radius:999px;font-size:10px;font-weight:700}.chip-http{background:#edf3ff;color:#315ba9}.chip-socks5{background:#ecf8f3;color:#18704f}.chip-free{background:#f2f4f7;color:#667085}.chip-custom{background:#fff5df;color:#95610b}.grade{font-size:12px;font-weight:780}.grade-s{color:#137452}.grade-a{color:#9b690f}.grade-b{color:#b75e20}.grade-c{color:#b43f52}.row-actions{display:flex;gap:5px}.mini-btn{width:30px;height:30px;border:1px solid var(--line);border-radius:8px;background:#fff;display:grid;place-items:center;cursor:pointer;color:#657185}.mini-btn:hover{background:#f3f6fb;color:var(--ink)}.mini-btn.danger{color:var(--bad);border-color:#efcbd2}.mini-btn .icon{width:14px;height:14px}.empty-state{min-height:260px;display:grid;place-items:center;text-align:center;color:var(--muted);padding:40px}.empty-state strong{display:block;color:var(--ink);font-size:14px;margin-bottom:4px}.skeleton{height:14px;border-radius:7px;background:linear-gradient(90deg,#eef1f5,#f8fafc,#eef1f5);background-size:220% 100%;animation:shimmer 1.3s infinite}.loading-rows{display:grid;gap:18px;padding:24px}
.pagination{min-height:54px;padding:9px 13px;border-top:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;gap:12px}.page-summary{font-size:11px;color:var(--muted)}.page-actions{display:flex;align-items:center;gap:7px}.page-index{min-width:82px;text-align:center;font-size:11px;color:var(--muted);font-variant-numeric:tabular-nums}
.subscription-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.subscription{background:var(--surface);border:1px solid var(--line);border-radius:15px;padding:15px;display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.sub-main{min-width:0}.sub-name{font-size:13px;font-weight:710;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.sub-meta{font-size:10px;color:var(--muted);margin-top:5px}.sub-state{display:inline-flex;align-items:center;gap:6px;font-size:10px;color:var(--good);margin-top:8px}.sub-state:before{content:"";width:6px;height:6px;border-radius:50%;background:currentColor}.sub-controls{display:flex;gap:5px}.contribute{border:1px dashed #bac9e8;background:var(--accent-soft);border-radius:15px;padding:17px;display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:11px}.contribute h3{font-size:13px}.contribute p{font-size:10px;color:#64728a;margin-top:3px}
.source-card{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);overflow:auto}.source-table{width:100%;min-width:820px;border-collapse:collapse}.source-table th,.source-table td{padding:11px 14px;border-bottom:1px solid #edf0f4;text-align:left;white-space:nowrap}.source-table th{background:var(--surface-soft);color:var(--muted);font-size:10px;font-weight:720}.source-table td{font-size:11px;color:#536074}.source-table tr:last-child td{border-bottom:0}.source-name{max-width:260px;overflow:hidden;text-overflow:ellipsis;color:var(--ink)!important;font-weight:660}.source-state{display:inline-flex;padding:3px 8px;border-radius:999px;font-size:9px;font-weight:750}.source-state.active{background:#eaf7f1;color:var(--good)}.source-state.degraded{background:#fff5df;color:var(--warn)}.source-state.disabled{background:#fff0f2;color:var(--bad)}
.log-card{background:#121a29;color:#cbd5e1;border-radius:var(--radius);overflow:hidden}.log-toolbar{padding:12px 15px;border-bottom:1px solid rgba(255,255,255,.08);display:flex;align-items:center;justify-content:space-between}.log-toolbar span{font-size:10px;color:#8794a8}.logs{height:360px;overflow:auto;padding:12px 15px;font:10px/1.72 var(--mono);contain:strict}.log-line{white-space:pre-wrap;overflow-wrap:anywhere;color:#9eabbf}.log-line.error{color:#fb8fa0}.log-line.success{color:#75d5ad}
.modal-layer{position:fixed;inset:0;background:rgba(18,27,43,.42);backdrop-filter:blur(10px);display:none;align-items:center;justify-content:center;padding:18px;z-index:100}.modal-layer.open{display:flex}.modal{width:min(760px,100%);max-height:min(860px,92vh);overflow:auto;background:rgba(255,255,255,.98);border:1px solid rgba(255,255,255,.75);border-radius:22px;box-shadow:0 32px 100px rgba(16,27,48,.25);transform-origin:center}.modal-sm{width:min(520px,100%)}.modal-head{position:sticky;top:0;z-index:2;padding:20px 22px 14px;background:rgba(255,255,255,.93);backdrop-filter:blur(18px);display:flex;align-items:center;justify-content:space-between;gap:12px}.modal-title{font-size:19px;font-weight:750;letter-spacing:-.025em}.modal-copy{font-size:10px;color:var(--muted);margin-top:3px}.modal-body{padding:5px 22px 22px}.form-section{padding:17px 0;border-top:1px solid var(--line)}.form-section:first-child{border-top:0}.form-section h3{font-size:12px;margin-bottom:12px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.form-group label{display:block;font-size:10px;font-weight:670;color:var(--muted);margin:0 0 6px}.form-help{font-size:9px;color:#929cac;margin-top:5px}.span-2{grid-column:1/-1}.segmented{display:grid;grid-template-columns:1fr 1fr;padding:3px;background:#eef1f5;border-radius:11px;gap:3px}.segmented button{border:0;border-radius:8px;padding:8px;background:transparent;color:var(--muted);font-size:11px;font-weight:670;cursor:pointer}.segmented button.active{background:#fff;color:var(--ink);box-shadow:0 1px 4px rgba(25,35,54,.1)}.dropzone{border:1px dashed #b9c4d5;border-radius:12px;padding:22px;text-align:center;color:var(--muted);font-size:11px;cursor:pointer}.dropzone:hover{border-color:#7898de;background:#f7f9ff}.modal-actions{position:sticky;bottom:0;background:rgba(255,255,255,.95);backdrop-filter:blur(16px);border-top:1px solid var(--line);padding:13px 22px;display:flex;justify-content:flex-end;gap:8px}
.toast{position:fixed;left:50%;bottom:24px;z-index:150;transform:translate(-50%,90px);opacity:0;background:#172033;color:#fff;border-radius:12px;padding:10px 15px;font-size:11px;font-weight:650;box-shadow:0 18px 44px rgba(18,28,45,.24);transition:transform .24s ease,opacity .24s ease;pointer-events:none}.toast.show{transform:translate(-50%,0);opacity:1}
.admin-only{display:none}
@keyframes shimmer{to{background-position:-220% 0}}
@media(max-width:1180px){.metric-grid{grid-template-columns:repeat(3,1fr)}.filterbar{grid-template-columns:1fr repeat(3,minmax(105px,auto))}.filterbar .secondary-filter{display:none}.split{grid-template-columns:1fr}}
@media(max-width:900px){.app-shell{display:block}.rail{position:relative;height:auto;padding:14px 16px;display:grid;grid-template-columns:auto 1fr auto;align-items:center}.brand{padding:0}.brand-sub,.nav-label{display:none}.nav{display:flex;justify-content:center}.nav a{padding:9px}.nav a span{display:none}.rail-foot{margin:0;padding:0;border:0}.role span:not(.role-dot){display:none}.rail-link{display:none}.workspace{padding-top:20px}}
@media(max-width:700px){.topbar{display:block}.top-actions{justify-content:flex-start;margin-top:16px}.status-main{align-items:flex-start}.status-total strong{font-size:28px}.metric-grid{grid-template-columns:repeat(2,1fr)}.filterbar{grid-template-columns:1fr 1fr}.filterbar .field{grid-column:1/-1}.filterbar .secondary-filter{display:block}.subscription-grid{grid-template-columns:1fr}.legend{grid-template-columns:repeat(2,1fr)}.form-grid{grid-template-columns:1fr}.span-2{grid-column:auto}.pagination{align-items:flex-start;flex-direction:column}.page-actions{width:100%;justify-content:space-between}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*,*:before,*:after{animation:none!important;transition-duration:.01ms!important}}
@media(prefers-reduced-transparency:reduce){.modal-layer,.modal-head,.modal-actions{backdrop-filter:none}.modal-layer{background:rgba(18,27,43,.72)}}
@media(prefers-contrast:more){:root{--line:#b8c1cf;--line-strong:#7e8999}.card,.metric,.table-card{border-width:2px}}
</style>
</head>
<body>
<div class="app-shell">
  <aside class="rail">
    <div class="brand"><div class="brand-mark">GP</div><div><div class="brand-name">GoProxy Plus</div><div class="brand-sub">Proxy orchestration</div></div></div>
    <div><div class="nav-label">Workspace</div><nav class="nav">
      <a href="#overview"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></svg><span>运行概览</span></a>
      <a href="#nodes"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="5" cy="12" r="2"/><circle cx="19" cy="5" r="2"/><circle cx="19" cy="19" r="2"/><path d="m7 11 10-5M7 13l10 5"/></svg><span>代理节点</span></a>
      <a href="#sources"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 6h16M4 12h16M4 18h16"/><circle cx="8" cy="6" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="10" cy="18" r="2"/></svg><span>来源质量</span></a>
      <a href="#subscriptions"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 5h16v14H4z"/><path d="m4 8 8 5 8-5"/></svg><span>订阅来源</span></a>
      <a href="#logs"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 5h16M4 12h16M4 19h10"/></svg><span>运行日志</span></a>
    </nav></div>
    <div class="rail-foot"><div class="role-line"><div class="role"><span class="role-dot"></span><span id="role-label">访客模式</span></div><a class="rail-link" id="session-link" href="/login">管理员登录</a></div></div>
  </aside>

  <main class="workspace"><div class="workspace-inner">
    <header class="topbar"><div><div class="eyebrow">Operations Console</div><h1 class="page-title">代理调度中心</h1><p class="page-copy">快速判断池子健康度，定位节点，并管理采集与订阅。</p></div>
      <div class="top-actions">
        <a class="btn btn-quiet" href="https://github.com/Fiz2Z/GoProxy-Plus" target="_blank" rel="noreferrer">GitHub</a>
        <button class="btn admin-only" data-action="settings"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.8l.1.1-2.9 2.9-.1-.1a1.7 1.7 0 0 0-1.8-.3 1.7 1.7 0 0 0-1 1.5V21h-4v-.1a1.7 1.7 0 0 0-1-1.5 1.7 1.7 0 0 0-1.8.3l-.1.1-2.9-2.9.1-.1a1.7 1.7 0 0 0 .3-1.8A1.7 1.7 0 0 0 3.1 14H3v-4h.1a1.7 1.7 0 0 0 1.5-1 1.7 1.7 0 0 0-.3-1.8l-.1-.1 2.9-2.9.1.1A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-1.5V3h4v.1a1.7 1.7 0 0 0 1 1.5 1.7 1.7 0 0 0 1.8-.3l.1-.1 2.9 2.9-.1.1a1.7 1.7 0 0 0-.3 1.8 1.7 1.7 0 0 0 1.5 1h.1v4h-.1a1.7 1.7 0 0 0-1.5 1Z"/></svg>系统设置</button>
        <button class="btn admin-only" data-action="latency"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20 12a8 8 0 1 1-2.3-5.7L20 8.6"/><path d="M20 4v4.6h-4.6"/></svg>刷新延迟</button>
        <button class="btn btn-primary admin-only" data-action="fetch"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 3v12M7 10l5 5 5-5"/><path d="M5 21h14"/></svg>抓取代理</button>
      </div>
    </header>

    <section id="overview">
      <div class="status-strip"><div class="status-main"><div class="status-copy"><span id="pool-orb" class="status-orb"></span><div><div id="pool-state" class="status-title">正在读取运行状态</div><div id="pool-update" class="status-meta">连接 GoProxy 服务中</div></div></div><div class="status-total"><strong id="pool-total">—</strong><span>当前可用节点</span></div></div></div>
      <div class="metric-grid">
        <div class="metric"><div class="metric-label">HTTP</div><div class="metric-value" id="metric-http">—</div><div class="metric-meta"><span id="metric-http-latency">—</span> ms 平均延迟</div></div>
        <div class="metric"><div class="metric-label">SOCKS5</div><div class="metric-value" id="metric-socks">—</div><div class="metric-meta"><span id="metric-socks-latency">—</span> ms 平均延迟</div></div>
        <div class="metric"><div class="metric-label">采集成功率</div><div class="metric-value" id="metric-collection">—</div><div class="metric-meta"><span id="metric-collection-count">0</span> 次结果反馈</div></div>
        <div class="metric"><div class="metric-label">代理连接率</div><div class="metric-value" id="metric-transport">—</div><div class="metric-meta"><span id="metric-transport-count">0</span> 次连接</div></div>
        <div class="metric"><div class="metric-label">B站风控率</div><div class="metric-value" id="metric-risk">—</div><div class="metric-meta"><span id="metric-risk-count">0</span> 次风控</div></div>
        <div class="metric"><div class="metric-label">隔离节点</div><div class="metric-value" id="metric-cooling">—</div><div class="metric-meta"><span id="metric-leases">0</span> 个活跃租约</div></div>
      </div>
      <div class="split">
        <div class="card"><div class="card-title">质量分布</div><div class="card-sub">按实际连接延迟划分，S/A 级优先参与加权轮换。</div><div class="quality-track"><span id="quality-s" class="quality-segment quality-s"></span><span id="quality-a" class="quality-segment quality-a"></span><span id="quality-b" class="quality-segment quality-b"></span><span id="quality-c" class="quality-segment quality-c"></span></div><div class="legend">
          <div class="legend-item"><span><i class="legend-dot quality-s"></i>S 级</span><strong id="count-s">0</strong></div><div class="legend-item"><span><i class="legend-dot quality-a"></i>A 级</span><strong id="count-a">0</strong></div><div class="legend-item"><span><i class="legend-dot quality-b"></i>B 级</span><strong id="count-b">0</strong></div><div class="legend-item"><span><i class="legend-dot quality-c"></i>C 级</span><strong id="count-c">0</strong></div>
        </div></div>
        <div class="card"><div class="card-title">调度器</div><div class="card-sub">应用粘性租约与代理冷却的实时状态。</div><div class="app-grid"><div class="app-stat"><span>租约有效期</span><strong id="app-ttl">—</strong></div><div class="app-stat"><span>活跃租约</span><strong id="app-leases">—</strong></div><div class="app-stat"><span>冷却节点</span><strong id="app-cooling">—</strong></div></div></div>
      </div>
    </section>

    <section id="nodes" class="section"><div class="section-head"><div><h2 class="section-title">代理节点</h2><p class="section-copy">按需检索，不再把整个代理池渲染到浏览器。</p></div><div class="section-actions"><button class="btn btn-icon" id="reload-nodes" title="刷新节点"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20 12a8 8 0 1 1-2.3-5.7L20 8.6"/><path d="M20 4v4.6h-4.6"/></svg></button></div></div>
      <div class="table-card"><div class="filterbar">
        <div class="field"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input id="node-search" class="input" type="search" placeholder="搜索地址、出口 IP 或位置" autocomplete="off"></div>
        <select id="filter-protocol" class="select"><option value="">全部协议</option><option value="http">HTTP</option><option value="socks5">SOCKS5</option></select>
        <select id="filter-grade" class="select"><option value="">全部等级</option><option value="S">S 级</option><option value="A">A 级</option><option value="B">B 级</option><option value="C">C 级</option></select>
        <select id="filter-country" class="select"><option value="">全部国家</option></select>
        <select id="filter-source" class="select secondary-filter"><option value="">全部来源</option><option value="free">免费池</option><option value="custom">订阅池</option></select>
        <select id="filter-sort" class="select secondary-filter"><option value="latency">延迟从低到高</option><option value="grade">等级优先</option><option value="usage">使用次数</option><option value="success">成功次数</option><option value="latency_desc">延迟从高到低</option></select>
      </div>
      <div id="node-table-region" class="table-scroll" aria-live="polite"><div class="loading-rows"><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div></div></div>
      <div class="pagination"><div id="page-summary" class="page-summary">正在加载节点…</div><div class="page-actions"><select id="page-size" class="select" style="width:auto"><option value="25">25 条</option><option value="50" selected>50 条</option><option value="100">100 条</option></select><button id="page-prev" class="btn">上一页</button><span id="page-index" class="page-index">— / —</span><button id="page-next" class="btn">下一页</button></div></div></div>
    </section>

    <section id="sources" class="section"><div class="section-head"><div><h2 class="section-title">免费来源质量</h2><p class="section-copy">展示最近一轮分阶段验证结果；低质量来源会自动冷却。</p></div></div><div id="source-stats" class="source-card"><div class="card">等待首轮来源统计…</div></div></section>

    <section id="subscriptions" class="section"><div class="section-head"><div><h2 class="section-title">订阅来源</h2><p class="section-copy">统一查看订阅、可用节点与自动刷新状态。</p></div><div class="section-actions"><button class="btn admin-only" data-action="refresh-subs">刷新全部</button><button class="btn btn-primary admin-only" data-action="add-sub">添加订阅</button></div></div>
      <div id="guest-contribute" class="contribute"><div><h3>贡献代理订阅</h3><p>访客可以提交订阅，节点会先经过验证再进入代理池。</p></div><button class="btn" data-action="contribute">提交订阅</button></div>
      <div id="subscription-list" class="subscription-grid"><div class="card">正在加载订阅…</div></div>
    </section>

    <section id="logs" class="section"><div class="section-head"><div><h2 class="section-title">运行日志</h2><p class="section-copy">日志独立低频刷新，不再触发节点表重绘。</p></div><button id="reload-logs" class="btn">刷新日志</button></div><div class="log-card"><div class="log-toolbar"><span>最近 100 条</span><span id="log-updated">等待刷新</span></div><div id="log-lines" class="logs"></div></div></section>
  </div></main>
</div>

<div id="settings-modal" class="modal-layer" role="dialog" aria-modal="true" aria-labelledby="settings-title"><div class="modal"><div class="modal-head"><div><h2 id="settings-title" class="modal-title">系统设置</h2><p class="modal-copy">配置代理池、验证、健康检查与地理过滤。</p></div><button class="btn btn-icon" data-close="settings-modal" aria-label="关闭"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m6 6 12 12M18 6 6 18"/></svg></button></div><div class="modal-body">
  <div class="form-section"><h3>代理使用模式</h3><div class="form-grid"><div class="form-group span-2"><label>出站代理选择策略</label><select id="cfg-custom-mode" class="select"><option value="mixed_custom_priority">混合 · 订阅优先</option><option value="mixed_free_priority">混合 · 免费优先</option><option value="mixed">混合 · 平等</option><option value="custom_only">仅订阅代理</option><option value="free_only">仅免费代理</option></select></div></div></div>
  <div class="form-section"><h3>免费代理池</h3><div class="form-grid"><div class="form-group"><label>池子容量</label><input id="cfg-pool-size" class="input" type="number" min="10" max="50000"></div><div class="form-group"><label>HTTP 占比</label><input id="cfg-http-ratio" class="input" type="number" min="0" max="1" step=".05"></div><div class="form-group"><label>每协议最小数</label><input id="cfg-min-per-protocol" class="input" type="number" min="1"></div><div class="form-group"><label>优化间隔（分钟）</label><input id="cfg-optimize-interval" class="input" type="number" min="10" step="10"></div><div class="form-group"><label>标准延迟（ms）</label><input id="cfg-max-latency" class="input" type="number" min="100"></div><div class="form-group"><label>健康延迟（ms）</label><input id="cfg-max-latency-healthy" class="input" type="number" min="100"></div><div class="form-group"><label>紧急延迟（ms）</label><input id="cfg-max-latency-emergency" class="input" type="number" min="100"></div><div class="form-group"><label>替换阈值</label><input id="cfg-replace-threshold" class="input" type="number" min=".1" max="1" step=".05"></div></div></div>
  <div class="form-section"><h3>订阅代理池</h3><div class="form-grid"><div class="form-group"><label>禁用节点探测（分钟）</label><input id="cfg-custom-probe" class="input" type="number" min="5"></div><div class="form-group"><label>默认刷新间隔（分钟）</label><input id="cfg-custom-refresh" class="input" type="number" min="10"></div></div></div>
  <div class="form-section"><h3>验证与健康检查</h3><div class="form-grid"><div class="form-group"><label>验证并发数</label><input id="cfg-concurrency" class="input" type="number" min="1"></div><div class="form-group"><label>验证超时（秒）</label><input id="cfg-timeout" class="input" type="number" min="1"></div><div class="form-group"><label>检查间隔（分钟）</label><input id="cfg-health-interval" class="input" type="number" min="1"></div><div class="form-group"><label>每批数量</label><input id="cfg-health-batch" class="input" type="number" min="1"></div></div></div>
  <div class="form-section"><h3>地理过滤</h3><div class="form-grid"><div class="form-group"><label>允许国家</label><input id="cfg-allowed-countries" class="input" placeholder="US, JP, KR"><div class="form-help">非空时作为白名单。</div></div><div class="form-group"><label>屏蔽国家</label><input id="cfg-blocked-countries" class="input" placeholder="CN"><div class="form-help">白名单为空时生效。</div></div></div></div>
  </div><div class="modal-actions"><button class="btn" data-close="settings-modal">取消</button><button id="save-settings" class="btn btn-primary">保存设置</button></div></div></div>

<div id="subscription-modal" class="modal-layer" role="dialog" aria-modal="true"><div class="modal modal-sm"><div class="modal-head"><div><h2 id="sub-modal-title" class="modal-title">添加订阅</h2><p id="sub-modal-copy" class="modal-copy">支持订阅 URL 与本地配置文件。</p></div><button class="btn btn-icon" data-close="subscription-modal" aria-label="关闭"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m6 6 12 12M18 6 6 18"/></svg></button></div><div class="modal-body">
  <div class="form-section"><div class="form-grid"><div class="form-group span-2"><label>名称</label><input id="sub-name" class="input" placeholder="例如：备用订阅"></div><div class="form-group span-2"><label>导入方式</label><div class="segmented"><button id="sub-mode-url" class="active" type="button">订阅 URL</button><button id="sub-mode-file" type="button">上传文件</button></div></div><div id="sub-url-group" class="form-group span-2"><label>订阅 URL</label><input id="sub-url" class="input" placeholder="https://example.com/sub?token=…"></div><div id="sub-file-group" class="form-group span-2" hidden><label>配置文件</label><label id="sub-dropzone" class="dropzone"><span id="sub-file-label">选择 .yaml、.txt、.conf 或 .json 文件</span><input id="sub-file" type="file" accept=".yaml,.yml,.txt,.conf,.json" hidden></label></div><div id="sub-refresh-group" class="form-group"><label>刷新间隔（分钟）</label><input id="sub-refresh" class="input" type="number" value="60" min="10"></div></div></div>
  </div><div class="modal-actions"><button class="btn" data-close="subscription-modal">取消</button><button id="submit-subscription" class="btn btn-primary">添加订阅</button></div></div></div>

<div id="toast" class="toast" role="status" aria-live="polite"></div>
<script>
(function(){
'use strict';
var state={admin:false,page:1,pageSize:50,pages:0,total:0,protocol:'',grade:'',country:'',source:'',sort:'latency',query:'',nodeAbort:null,nodeRequest:0,subscriptions:{},subMode:'url',contribute:false,fileContent:''};
var $=function(id){return document.getElementById(id)};
var icons={refresh:'<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20 12a8 8 0 1 1-2.3-5.7L20 8.6"/><path d="M20 4v4.6h-4.6"/></svg>',pause:'<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M9 5v14M15 5v14"/></svg>',play:'<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m8 5 11 7-11 7Z"/></svg>',trash:'<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13"/></svg>'};
function setText(id,value){var el=$(id);var text=value===undefined||value===null?'—':String(value);if(el&&el.textContent!==text)el.textContent=text}
function pct(value,count){return count?Number(value||0).toFixed(1)+'%':'—'}
function tone(el,value,inverse){if(!el)return;el.classList.remove('tone-good','tone-warn','tone-bad');var n=Number(value||0);if(inverse)el.classList.add(n<=10?'tone-good':n<=25?'tone-warn':'tone-bad');else el.classList.add(n>=85?'tone-good':n>=65?'tone-warn':'tone-bad')}
function toast(message){var el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(function(){el.classList.remove('show')},2400)}
async function api(path,options){var response=await fetch(path,options||{});if(response.status===401){location.href='/login';throw new Error('unauthorized')}var data=null;try{data=await response.json()}catch(e){}if(!response.ok)throw new Error(data&&data.error?data.error:'请求失败 '+response.status);return data}
async function loadAuth(){try{var auth=await api('/api/auth/check');state.admin=!!auth.isAdmin}catch(e){state.admin=false}document.querySelectorAll('.admin-only').forEach(function(el){el.style.display=state.admin?'inline-flex':'none'});setText('role-label',state.admin?'管理员模式':'访客模式');var link=$('session-link');link.textContent=state.admin?'退出登录':'管理员登录';link.href=state.admin?'/logout':'/login';$('guest-contribute').style.display=state.admin?'none':'flex'}
async function loadPool(){try{var p=await api('/api/pool/status');var poolState=String(p.State||p.state||'unknown');setText('pool-state',({healthy:'运行稳定',warning:'容量预警',critical:'节点不足',emergency:'应急模式'})[poolState]||poolState);setText('pool-update','状态实时更新 · '+new Date().toLocaleTimeString());setText('pool-total',p.Total||p.total||0);setText('metric-http',p.HTTP||p.http||0);setText('metric-socks',p.SOCKS5||p.socks5||0);setText('metric-http-latency',p.AvgLatencyHTTP||p.avg_latency_http||'—');setText('metric-socks-latency',p.AvgLatencySocks5||p.avg_latency_socks5||'—');var orb=$('pool-orb');orb.className='status-orb '+(poolState==='healthy'?'':poolState)}catch(e){setText('pool-state','状态读取失败');setText('pool-update',e.message);$('pool-orb').className='status-orb critical'}}
async function loadApplication(){try{var a=await api('/api/application/status');setText('metric-collection',pct(a.collection_success_rate,a.collection_requests));setText('metric-transport',pct(a.transport_success_rate,a.transport_attempts));setText('metric-risk',pct(a.risk_rate,a.collection_requests));setText('metric-cooling',a.cooling_proxies||0);setText('metric-leases',a.active_leases||0);setText('metric-collection-count',a.collection_requests||0);setText('metric-transport-count',a.transport_attempts||0);setText('metric-risk-count',a.risk_failures||0);setText('app-ttl',(a.lease_ttl_seconds||'—')+(a.lease_ttl_seconds?'s':''));setText('app-leases',a.active_leases||0);setText('app-cooling',a.cooling_proxies||0);tone($('metric-collection'),a.collection_success_rate,false);tone($('metric-transport'),a.transport_success_rate,false);tone($('metric-risk'),a.risk_rate,true)}catch(e){}}
async function loadQuality(){try{var q=await api('/api/pool/quality');var values=['S','A','B','C'];var total=values.reduce(function(sum,k){return sum+Number(q[k]||0)},0);values.forEach(function(k){setText('count-'+k.toLowerCase(),q[k]||0);$('quality-'+k.toLowerCase()).style.width=(total?Number(q[k]||0)/total*100:0)+'%'})}catch(e){}}
function showNodeLoading(){var region=$('node-table-region');region.replaceChildren();var wrap=document.createElement('div');wrap.className='loading-rows';for(var i=0;i<5;i++){var line=document.createElement('div');line.className='skeleton';wrap.appendChild(line)}region.appendChild(wrap)}
function cell(text,className){var td=document.createElement('td');td.textContent=text===undefined||text===null||text===''?'—':String(text);if(className)td.className=className;return td}
function iconButton(action,address,html,label,danger){var b=document.createElement('button');b.className='mini-btn'+(danger?' danger':'');b.dataset.action=action;b.dataset.address=address;b.innerHTML=html;b.title=label;b.setAttribute('aria-label',label);return b}
function renderNodes(items){var region=$('node-table-region');region.replaceChildren();if(!items.length){var empty=document.createElement('div');empty.className='empty-state';empty.innerHTML='<div><strong>没有匹配的节点</strong><span>调整筛选条件后再试。</span></div>';region.appendChild(empty);return}var table=document.createElement('table');table.className='node-table';var head=document.createElement('thead');head.innerHTML='<tr><th>等级</th><th>协议</th><th>代理地址</th><th>出口 IP</th><th>位置</th><th>延迟</th><th>来源</th><th>使用 / 成功</th>'+(state.admin?'<th>操作</th>':'')+'</tr>';table.appendChild(head);var body=document.createElement('tbody');var frag=document.createDocumentFragment();items.forEach(function(p){var tr=document.createElement('tr');tr.className='node-row';tr.appendChild(cell(p.quality_grade||'C','grade grade-'+String(p.quality_grade||'C').toLowerCase()));var proto=document.createElement('td');var protoChip=document.createElement('span');protoChip.className='chip chip-'+p.protocol;protoChip.textContent=String(p.protocol||'').toUpperCase();proto.appendChild(protoChip);tr.appendChild(proto);var addr=document.createElement('td');var copy=document.createElement('button');copy.className='address-btn mono';copy.dataset.action='copy';copy.dataset.address=p.address;copy.textContent=p.address;copy.title='点击复制';addr.appendChild(copy);tr.appendChild(addr);tr.appendChild(cell(p.exit_ip,'mono'));tr.appendChild(cell(p.exit_location));tr.appendChild(cell(p.latency>0?p.latency+' ms':'—','mono'));var source=document.createElement('td');var sourceChip=document.createElement('span');sourceChip.className='chip chip-'+(p.source==='custom'?'custom':'free');sourceChip.textContent=p.source==='custom'?(state.subscriptions[p.subscription_id]||'订阅池'):'免费池';source.appendChild(sourceChip);tr.appendChild(source);tr.appendChild(cell((p.use_count||0)+' / '+(p.success_count||0),'mono'));if(state.admin){var actions=document.createElement('td');var group=document.createElement('div');group.className='row-actions';group.appendChild(iconButton('refresh-node',p.address,icons.refresh,'刷新节点',false));group.appendChild(iconButton('delete-node',p.address,icons.trash,'删除节点',true));actions.appendChild(group);tr.appendChild(actions)}frag.appendChild(tr)});body.appendChild(frag);table.appendChild(body);region.appendChild(table)}
function updateCountries(countries){var select=$('filter-country');var current=state.country;var next=document.createDocumentFragment();var first=document.createElement('option');first.value='';first.textContent='全部国家';next.appendChild(first);(countries||[]).forEach(function(code){var option=document.createElement('option');option.value=code;option.textContent=code;next.appendChild(option)});select.replaceChildren(next);if(current&&(countries||[]).indexOf(current)>=0)select.value=current;else if(current){state.country='';select.value=''}}
async function loadNodes(){if(state.nodeAbort)state.nodeAbort.abort();state.nodeAbort=new AbortController();var seq=++state.nodeRequest;showNodeLoading();var p=new URLSearchParams({paged:'1',page:String(state.page),page_size:String(state.pageSize),sort:state.sort});if(state.protocol)p.set('protocol',state.protocol);if(state.grade)p.set('grade',state.grade);if(state.country)p.set('country',state.country);if(state.source)p.set('source',state.source);if(state.query)p.set('q',state.query);try{var data=await api('/api/proxies?'+p.toString(),{signal:state.nodeAbort.signal});if(seq!==state.nodeRequest)return;state.page=data.page||1;state.pages=data.pages||0;state.total=data.total||0;updateCountries(data.countries||[]);renderNodes(data.items||[]);setText('page-summary','共 '+state.total.toLocaleString()+' 个匹配节点，每页仅渲染 '+state.pageSize+' 条');setText('page-index',state.pages?state.page+' / '+state.pages:'0 / 0');$('page-prev').disabled=state.page<=1;$('page-next').disabled=!state.pages||state.page>=state.pages}catch(e){if(e.name!=='AbortError'){renderNodes([]);setText('page-summary','加载失败：'+e.message)}}}
async function loadSubscriptions(){try{var list=await api('/api/subscriptions');state.subscriptions={};list.forEach(function(s){state.subscriptions[s.id]=s.name||'订阅'});var root=$('subscription-list');root.replaceChildren();if(!list.length){var empty=document.createElement('div');empty.className='card';empty.textContent='尚未添加订阅。';root.appendChild(empty);return}var frag=document.createDocumentFragment();list.forEach(function(s){var card=document.createElement('article');card.className='subscription';var main=document.createElement('div');main.className='sub-main';var name=document.createElement('div');name.className='sub-name';name.textContent=s.name||'未命名订阅';var meta=document.createElement('div');meta.className='sub-meta';var active=s.active_count||0,disabled=s.disabled_count||0;meta.textContent=(active+disabled)+' 个节点 · '+active+' 可用'+(disabled?' · '+disabled+' 待恢复':'');var status=document.createElement('div');status.className='sub-state';status.textContent=s.status==='active'?'正在自动刷新':'已暂停';main.append(name,meta,status);card.appendChild(main);if(state.admin){var controls=document.createElement('div');controls.className='sub-controls';controls.appendChild(iconButton('refresh-sub',String(s.id),icons.refresh,'刷新订阅',false));controls.appendChild(iconButton('toggle-sub',String(s.id),s.status==='active'?icons.pause:icons.play,s.status==='active'?'暂停订阅':'启用订阅',false));controls.appendChild(iconButton('delete-sub',String(s.id),icons.trash,'删除订阅',true));card.appendChild(controls)}frag.appendChild(card)});root.appendChild(frag)}catch(e){$('subscription-list').textContent='订阅加载失败：'+e.message}}
function sourceLabel(value){try{var u=new URL(value);var part=u.pathname.split('/').filter(Boolean)[0]||'';return u.hostname+(part?' / '+part:'')}catch(e){return value||'未知来源'}}
function stageRate(value,total){return total?((Number(value||0)/Number(total))*100).toFixed(2)+'%':'—'}
async function loadSources(){try{var data=await api('/api/sources/stats');var items=data.items||[];var root=$('source-stats');root.replaceChildren();if(!items.length){var empty=document.createElement('div');empty.className='empty-state';empty.innerHTML='<div><strong>等待首轮验证</strong><span>完成一轮代理抓取后会显示各来源质量。</span></div>';root.appendChild(empty);return}var table=document.createElement('table');table.className='source-table';var head=document.createElement('thead');head.innerHTML='<tr><th>来源</th><th>质量状态</th><th>候选</th><th>基础连通</th><th>B站 HTTPS</th><th>出口识别</th><th>最终入池</th></tr>';table.appendChild(head);var body=document.createElement('tbody');var frag=document.createDocumentFragment();items.forEach(function(s){var total=Number(s.last_candidates||0);var tr=document.createElement('tr');var name=cell(sourceLabel(s.url),'source-name');name.title=s.url||'';tr.appendChild(name);var status=document.createElement('td');var badge=document.createElement('span');var quality=s.quality_status||'active';badge.className='source-state '+quality;badge.textContent=quality==='disabled'?'已停用':quality==='degraded'?'冷却中':'正常';status.appendChild(badge);tr.appendChild(status);tr.appendChild(cell(total.toLocaleString(),'mono'));tr.appendChild(cell(stageRate(s.last_base,total),'mono'));tr.appendChild(cell(stageRate(s.last_tls,total),'mono'));tr.appendChild(cell(stageRate(s.last_exit,total),'mono'));tr.appendChild(cell((s.last_admitted||0)+' · '+stageRate(s.last_admitted,total),'mono'));frag.appendChild(tr)});body.appendChild(frag);table.appendChild(body);root.appendChild(table)}catch(e){$('source-stats').textContent='来源统计加载失败：'+e.message}}
async function loadLogs(){if(document.hidden)return;try{var data=await api('/api/logs');var root=$('log-lines');var nearBottom=root.scrollHeight-root.scrollTop-root.clientHeight<60;var frag=document.createDocumentFragment();(data.lines||[]).forEach(function(text){var line=document.createElement('div');line.className='log-line';var lower=String(text).toLowerCase();if(lower.indexOf('error')>=0||lower.indexOf('failed')>=0||lower.indexOf('失败')>=0)line.classList.add('error');else if(lower.indexOf('success')>=0||lower.indexOf('completed')>=0||lower.indexOf('成功')>=0)line.classList.add('success');line.textContent=text;frag.appendChild(line)});root.replaceChildren(frag);if(nearBottom)root.scrollTop=root.scrollHeight;setText('log-updated','更新于 '+new Date().toLocaleTimeString())}catch(e){setText('log-updated','刷新失败')}}
function openModal(id){$(id).classList.add('open');document.body.style.overflow='hidden';var focus=$(id).querySelector('input,select,button');if(focus)setTimeout(function(){focus.focus()},0)}function closeModal(id){$(id).classList.remove('open');document.body.style.overflow=''}
function fieldValue(id,value){var el=$(id);if(el)el.value=value===undefined||value===null?'':value}
async function openSettings(){try{var c=await api('/api/config');fieldValue('cfg-pool-size',c.pool_max_size);fieldValue('cfg-http-ratio',c.pool_http_ratio);fieldValue('cfg-min-per-protocol',c.pool_min_per_protocol);fieldValue('cfg-max-latency',c.max_latency_ms);fieldValue('cfg-max-latency-healthy',c.max_latency_healthy);fieldValue('cfg-max-latency-emergency',c.max_latency_emergency);fieldValue('cfg-concurrency',c.validate_concurrency);fieldValue('cfg-timeout',c.validate_timeout);fieldValue('cfg-health-interval',c.health_check_interval);fieldValue('cfg-health-batch',c.health_check_batch_size);fieldValue('cfg-optimize-interval',c.optimize_interval);fieldValue('cfg-replace-threshold',c.replace_threshold);fieldValue('cfg-blocked-countries',(c.blocked_countries||[]).join(','));fieldValue('cfg-allowed-countries',(c.allowed_countries||[]).join(','));var mode=c.custom_proxy_mode||'mixed';if(mode==='mixed'&&c.custom_priority)mode='mixed_custom_priority';else if(mode==='mixed'&&c.custom_free_priority)mode='mixed_free_priority';fieldValue('cfg-custom-mode',mode);fieldValue('cfg-custom-probe',c.custom_probe_interval||10);fieldValue('cfg-custom-refresh',c.custom_refresh_interval||60);openModal('settings-modal')}catch(e){toast('配置读取失败：'+e.message)}}
function number(id,float){return float?parseFloat($(id).value):parseInt($(id).value,10)}function countries(id){return $(id).value.split(',').map(function(v){return v.trim().toUpperCase()}).filter(Boolean)}
async function saveSettings(){var mode=$('cfg-custom-mode').value;var payload={pool_max_size:number('cfg-pool-size'),pool_http_ratio:number('cfg-http-ratio',true),pool_min_per_protocol:number('cfg-min-per-protocol'),max_latency_ms:number('cfg-max-latency'),max_latency_healthy:number('cfg-max-latency-healthy'),max_latency_emergency:number('cfg-max-latency-emergency'),validate_concurrency:number('cfg-concurrency'),validate_timeout:number('cfg-timeout'),health_check_interval:number('cfg-health-interval'),health_check_batch_size:number('cfg-health-batch'),optimize_interval:number('cfg-optimize-interval'),replace_threshold:number('cfg-replace-threshold',true),blocked_countries:countries('cfg-blocked-countries'),allowed_countries:countries('cfg-allowed-countries'),custom_proxy_mode:mode==='custom_only'||mode==='free_only'?mode:'mixed',custom_priority:mode==='mixed_custom_priority',custom_free_priority:mode==='mixed_free_priority',custom_probe_interval:number('cfg-custom-probe'),custom_refresh_interval:number('cfg-custom-refresh')};try{await api('/api/config/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});closeModal('settings-modal');toast('设置已保存');loadOverview()}catch(e){toast('保存失败：'+e.message)}}
function setSubMode(mode){state.subMode=mode;$('sub-mode-url').classList.toggle('active',mode==='url');$('sub-mode-file').classList.toggle('active',mode==='file');$('sub-url-group').hidden=mode!=='url';$('sub-file-group').hidden=mode!=='file';$('sub-refresh-group').hidden=state.contribute}
function openSubscription(contribute){state.contribute=!!contribute;state.fileContent='';fieldValue('sub-name','');fieldValue('sub-url','');$('sub-file-label').textContent='选择 .yaml、.txt、.conf 或 .json 文件';setText('sub-modal-title',contribute?'贡献代理订阅':'添加订阅');setText('sub-modal-copy',contribute?'提交后会验证可用性，不会公开订阅地址。':'支持订阅 URL 与本地配置文件。');setText('submit-subscription',contribute?'提交订阅':'添加订阅');setSubMode('url');openModal('subscription-modal')}
async function submitSubscription(){var payload={name:$('sub-name').value.trim()||(state.contribute?'访客贡献':'未命名订阅')};if(state.subMode==='url'){payload.url=$('sub-url').value.trim();if(!payload.url){toast('请输入订阅 URL');return}}else{if(!state.fileContent){toast('请选择配置文件');return}payload.file_content=state.fileContent}if(!state.contribute)payload.refresh_min=parseInt($('sub-refresh').value,10)||60;var button=$('submit-subscription');button.disabled=true;try{await api(state.contribute?'/api/subscription/contribute':'/api/subscription/add',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});closeModal('subscription-modal');toast(state.contribute?'感谢贡献，节点正在验证':'订阅已添加');setTimeout(loadSubscriptions,1200)}catch(e){toast('提交失败：'+e.message)}finally{button.disabled=false}}
async function post(path,payload){return api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:payload?JSON.stringify(payload):undefined})}
async function handleAction(action,value){try{if(action==='settings')return openSettings();if(action==='fetch'){if(confirm('开始抓取新的代理节点？')){await post('/api/fetch');toast('抓取任务已启动')}}else if(action==='latency'){if(confirm('刷新全部节点延迟？这会产生较多网络请求。')){await post('/api/refresh-latency');toast('延迟刷新已启动')}}else if(action==='add-sub')openSubscription(false);else if(action==='contribute')openSubscription(true);else if(action==='refresh-subs'){await post('/api/subscription/refresh-all');toast('订阅刷新已启动');setTimeout(loadSubscriptions,1000)}else if(action==='copy'){await navigator.clipboard.writeText(value);toast('已复制 '+value)}else if(action==='refresh-node'){await post('/api/proxy/refresh',{address:value});toast('节点验证已启动')}else if(action==='delete-node'){if(confirm('删除节点 '+value+'？')){await post('/api/proxy/delete',{address:value});toast('节点已删除');loadNodes()}}else if(action==='refresh-sub'){await post('/api/subscription/refresh',{id:Number(value)});toast('订阅刷新已启动');setTimeout(loadSubscriptions,1000)}else if(action==='toggle-sub'){await post('/api/subscription/toggle',{id:Number(value)});loadSubscriptions()}else if(action==='delete-sub'){if(confirm('删除这个订阅及关联节点？')){await post('/api/subscription/delete',{id:Number(value)});toast('订阅已删除');loadSubscriptions()}}}catch(e){toast('操作失败：'+e.message)}}
function loadOverview(){return Promise.allSettled([loadPool(),loadApplication(),loadQuality()])}
function bind(){document.addEventListener('click',function(e){var close=e.target.closest('[data-close]');if(close){closeModal(close.dataset.close);return}var target=e.target.closest('[data-action]');if(target)handleAction(target.dataset.action,target.dataset.address||'')});document.querySelectorAll('.modal-layer').forEach(function(layer){layer.addEventListener('pointerdown',function(e){if(e.target===layer)closeModal(layer.id)})});document.addEventListener('keydown',function(e){if(e.key==='Escape')document.querySelectorAll('.modal-layer.open').forEach(function(m){closeModal(m.id)})});var debounce;var search=$('node-search');search.addEventListener('input',function(){clearTimeout(debounce);debounce=setTimeout(function(){state.query=search.value.trim();state.page=1;loadNodes()},180)});[['filter-protocol','protocol'],['filter-grade','grade'],['filter-country','country'],['filter-source','source'],['filter-sort','sort']].forEach(function(pair){$(pair[0]).addEventListener('change',function(){state[pair[1]]=this.value;state.page=1;loadNodes()})});$('page-size').addEventListener('change',function(){state.pageSize=Number(this.value);state.page=1;loadNodes()});$('page-prev').addEventListener('click',function(){if(state.page>1){state.page--;loadNodes()}});$('page-next').addEventListener('click',function(){if(state.page<state.pages){state.page++;loadNodes()}});$('reload-nodes').addEventListener('click',loadNodes);$('reload-logs').addEventListener('click',loadLogs);$('save-settings').addEventListener('click',saveSettings);$('sub-mode-url').addEventListener('click',function(){setSubMode('url')});$('sub-mode-file').addEventListener('click',function(){setSubMode('file')});$('sub-file').addEventListener('change',function(){var file=this.files&&this.files[0];if(!file)return;var reader=new FileReader();reader.onload=function(){state.fileContent=String(reader.result||'');$('sub-file-label').textContent=file.name+' · '+(state.fileContent.length/1024).toFixed(1)+' KB'};reader.readAsText(file)});$('submit-subscription').addEventListener('click',submitSubscription)}
async function start(){bind();await loadAuth();await Promise.allSettled([loadOverview(),loadSubscriptions(),loadSources(),loadLogs()]);loadNodes();setInterval(function(){if(!document.hidden)loadOverview()},10000);setInterval(loadLogs,15000);setInterval(function(){if(!document.hidden){loadSubscriptions();loadSources()}},60000);document.addEventListener('visibilitychange',function(){if(!document.hidden){loadOverview();loadSources();loadLogs()}})}
start();
})();
</script>
</body>
</html>`
